#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:8000/eureka/
#spring:
#  application:
#    name: oeder
#server:
#  port: 9500
#product:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule